### ISSUE TITLE
gifsearch.random() returns undefined

### ISSUE THREAD

**Issue by iwantpizza10** [selcher/gif-search#2]

**Comment by selcher** [comment]
@iwantpizza10  Thank you for reporting about the issue.

gif-search currently uses the public api key of the Giphy API.
Unfortunately, the public api key seems to have been decomissioned.
[Using the Giphy API with Free API Key](https://rapidapi.com/giphy/api/Giphy/details)

Try creating a unique api key at [Giphy](https://developers.giphy.com/), then use it to perform a gif search:
```
// Change the API Key
gifSearch.setAPIKey('my-api-key');

// Search for a random gif
gifSearch.random('cat').then(
    gifUrl => console.log(gifUrl)
);
```

I'll update the docs and code to require users to provide an api key when performing a search.

**Comment by selcher** [comment]
@iwantpizza10  Confirmed that the  random api does return undefined.
I'll release a fix for this soon.

**Comment by iwantpizza10** [comment]
i did set the api key

**Comment by selcher** [comment]
Try the latest version. It has the fix.
